name: vehicle_tracking_system
description: A comprehensive vehicle tracking system using mobile GPS with real-time monitoring, geofencing, and driver behavior analysis.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Platform Essentials
  cupertino_icons: ^1.0.8
  provider: ^6.1.1

  # Firebase Core + Services
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.14.0
  firebase_database: ^10.4.0
  firebase_messaging: ^14.7.0
  cloud_functions: ^4.6.0

  # Location & Mapping
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  geocoding: ^3.0.0

  # Sensors for driver behavior analysis
  sensors_plus: ^4.0.2

  # Background Services & Notifications
  flutter_local_notifications: ^17.0.0
  # background_fetch: ^1.2.1  # Temporarily commented out due to dependency resolution issues
  flutter_background_service: ^5.0.5
  # workmanager: ^0.5.2  # Temporarily commented out due to compatibility issues
  # State Management & Architecture
  get: ^4.6.6
  get_it: ^7.6.4

  # Utility & Data
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  device_info_plus: ^10.1.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.2.2
  
  # UI & Animation
  lottie: ^3.0.0
  flutter_spinkit: ^5.2.0
  
  # Data Processing
  intl: ^0.19.0
  crypto: ^3.0.3
  http: ^1.1.2
  
  # Charts & Analytics
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^24.1.41
  
  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.12.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
